

all: hello.exe .symbolic


clean : .SYMBOLIC
	@if exist *.exe del *.exe
	@if exist *.err del *.err
	@if exist *.lib del *.lib
	@if exist *.obj del *.obj
	@if exist *.map del *.map

	

.cxx.exe:
	wcl -k9000 -d1 -ml -I=.. -I=..\dos $[@ ..\dos\xlib.lib  ..\src\fltk.lib

